name: 🎁 Feature Request
description: Do you have an idea or suggestion to make this even better?
labels: 
  - feature
title: '[Feature]: '
body:
  - type: markdown 
    attributes:
      value: |
        Thank you for your interest in improving the Awesome List Generator! 
        Before submitting a feature request, please check to see if it has already been suggested.
  - type: textarea
    attributes:
      label: Feature Description
      description: |
        Please provide a clear and concise description of the feature you would like to see added.
  - type: textarea
    attributes:
      label: Use Case
      description: |
        Describe how this feature would be used and why it is important.
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Provide any additional context or information that may help in understanding the feature request.
  - type: dropdown
    attributes:
      label: Would you be interested on work on this feature
      options:
        - "Yes"
        - "No"
      default: 1